FROM ghcr.io/tiiuae/fog-ros-baseimage-builder:v3.3.0

# config dependencies install
ARG DEBIAN_FRONTEND=noninteractive
RUN echo -e '\
APT::Install-Recommends "0";\n\
APT::Install-Suggests "0";\n\
' > /etc/apt/apt.conf.d/01norecommend

ARG UNDERLAY_WS=/main_ws/underlay_ws
ARG OVERLAY_WS=/main_ws/overlay_ws

WORKDIR $UNDERLAY_WS
COPY ddsrouter_v340.repos $UNDERLAY_WS/src/ddsrouter_experiments/underlay.repos

# Import the underlay dependencies that doesn't exist in SDK image
RUN vcs import ./src/ < $UNDERLAY_WS/src/ddsrouter_experiments/underlay.repos
# COPY locator.patch $UNDERLAY_WS/src/fastdds_statistics_backend/locator.patch

RUN ls -la $UNDERLAY_WS/src && \
    . /usr/bin/ros_setup.bash && \
    colcon build --event-handlers console_direct+ --cmake-args -DBUILD_TESTING=0 -DLOG_INFO=ON -DSECURITY=ON -DCOMPILE_EXAMPLES=ON

# RUN apt-get update && \
#     apt-get install -y \
#       nlohmann-json-dev \
#     && rm -rf /var/lib/apt/lists/*

# WORKDIR $OVERLAY_WS

# COPY . $OVERLAY_WS/src/fastdds_monitor_tutorial

# RUN . $UNDERLAY_WS/install/setup.sh && \
#     . /usr/bin/ros_setup.bash && \
#     colcon build --cmake-args -DBUILD_TESTING=0 && \
#     cp $OVERLAY_WS/install/fastdds_monitor_tutorial/lib/fastdds_monitor_tutorial/fastdds_monitor $OVERLAY_WS/

# ENV FASTDDS_DEFAULT_PROFILES_FILE=/config/FASTRTPS_PROFILES_WHITELIST.xml
# ENV FASTRTPS_DEFAULT_PROFILES_FILE=/config/FASTRTPS_PROFILES_WHITELIST.xml
RUN unset FASTDDS_DEFAULT_PROFILES_FILE
RUN unset FASTRTPS_DEFAULT_PROFILES_FILE
ENV UNDERLAY_WS=$UNDERLAY_WS

# COPY . $UNDERLAY_WS/src/ddsrouter_experiments
# COPY configurations /$UNDERLAY_WS/src/ddsrouter_experiments/configurations
# COPY scripts /$UNDERLAY_WS/src/ddsrouter_experiments/scripts

COPY run.bash /root/run.bash

RUN chmod +x /root/run.bash

ENTRYPOINT ["/root/run.bash" ]

# ENTRYPOINT ["/bin/bash", "-c", ". $UNDERLAY_WS/install/setup.sh && . /usr/bin/ros_setup.bash && exec /bin/bash"]
